#!/bin/sh
# Build a #[handler] program and serve it locally on workerd (no Cloudflare
# account or network needed). Requests are routed into a Durable Object
# (`-target do`) whose SQLite storage lives in OUT/.state, so data
# survives restarts.
#
#   scripts/dev.sh <file.kek>
#
# Environment:
#   PORT=8787        listening port
#   OUT=dir          output directory (default out/<name>)
#   OUTBOX=log|fetch outbox delivery (default log: print entries instead of POSTing)
#   SHARD=global     KEKKAI_DO_SHARD (see docs/runtime.md)
set -eu

file=${1:?usage: scripts/dev.sh <file.kek>}
name=$(basename "$file" .kek)
out=${OUT:-out/$name}
port=${PORT:-8787}

./kek build -target do -o "$out" "$file"
out=$(cd "$out" && pwd)
mkdir -p "$out/.state"
cat >"$out/workerd.capnp" <<EOF2
# Generated by scripts/dev.sh.
using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
    (name = "main", worker = .worker),
    (name = "state", disk = (path = "$out/.state", writable = true)),
    (name = "internet", network = (allow = ["public"])),
  ],
  sockets = [(name = "http", address = "127.0.0.1:$port", http = (), service = "main")],
);

const worker :Workerd.Worker = (
  modules = [
    (name = "worker.js", esModule = embed "worker.js"),
    (name = "kekkai_runtime.js", esModule = embed "kekkai_runtime.js"),
    (name = "kekkai_meta.js", esModule = embed "kekkai_meta.js"),
    (name = "module.wasm", wasm = embed "module.wasm"),
  ],
  compatibilityDate = "2026-09-01",
  bindings = [
    (name = "KEKKAI_OUTBOX", text = "${OUTBOX:-log}"),
    (name = "KEKKAI_DO_SHARD", text = "${SHARD:-global}"),
    (name = "KEKKAI_DO", durableObjectNamespace = "KekkaiObject"),
  ],
  durableObjectNamespaces = [(className = "KekkaiObject", uniqueKey = "kekkai-dev-$name", enableSql = true)],
  durableObjectStorage = (localDisk = "state"),
  globalOutbound = "internet",
);
EOF2
echo "serving $file on http://127.0.0.1:$port (state in $out/.state)"
exec workerd serve "$out/workerd.capnp"
