#!/bin/sh
# Build a #[handler] program and serve it locally on workerd (no Cloudflare
# account or network needed). Requests are routed into a Durable Object
# (`-target do`) whose SQLite storage lives in OUT/.state, so data
# survives restarts.
#
#   scripts/dev.sh <file.kek>
#
# Environment:
#   PORT=8787        listening port
#   OUT=dir          output directory (default out/<name>)
#   OUTBOX=log|fetch outbox delivery (default log: print entries instead of POSTing)
#   SHARD=global     KEKKAI_DO_SHARD (see docs/runtime.md)
#   ASSETS=dir       also serve the static files in dir, like Workers Static
#                    Assets: a GET for an existing file (`/` is index.html)
#                    gets the file, everything else goes to the program
set -eu

file=${1:?usage: scripts/dev.sh <file.kek>}
name=$(basename "$file" .kek)
out=${OUT:-out/$name}
port=${PORT:-8787}

./kek build -target do -o "$out" "$file"
out=$(cd "$out" && pwd)
mkdir -p "$out/.state"
front=main
assets_service=
router=
if [ -n "${ASSETS:-}" ]; then
	assets=$(cd "$ASSETS" && pwd)
	front=assets_router
	assets_service="
    (name = \"assets_router\", worker = .router),
    (name = \"assets\", disk = (path = \"$assets\")),"
	cat >"$out/assets_router.js" <<'EOF2'
// Generated by scripts/dev.sh: static files first, then the program.
const types = { html: "text/html; charset=utf-8", js: "text/javascript", css: "text/css", json: "application/json",
  svg: "image/svg+xml", png: "image/png", ico: "image/x-icon", txt: "text/plain; charset=utf-8" };
export default {
  async fetch(req, env) {
    if (req.method === "GET" || req.method === "HEAD") {
      const url = new URL(req.url);
      const path = url.pathname.endsWith("/") ? url.pathname + "index.html" : url.pathname;
      const r = await env.ASSETS.fetch("http://assets" + path, { method: req.method });
      if (r.ok) {
        const headers = new Headers(r.headers);
        headers.set("content-type", types[path.split(".").pop()] ?? "application/octet-stream");
        return new Response(r.body, { status: r.status, headers });
      }
    }
    return env.APP.fetch(req);
  },
};
EOF2
	router='
const router :Workerd.Worker = (
  modules = [(name = "assets_router.js", esModule = embed "assets_router.js")],
  compatibilityDate = "2026-09-01",
  bindings = [(name = "ASSETS", service = "assets"), (name = "APP", service = "main")],
);'
fi
cat >"$out/workerd.capnp" <<EOF2
# Generated by scripts/dev.sh.
using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
    (name = "main", worker = .worker),$assets_service
    (name = "state", disk = (path = "$out/.state", writable = true)),
    (name = "internet", network = (allow = ["public"])),
  ],
  sockets = [(name = "http", address = "127.0.0.1:$port", http = (), service = "$front")],
);

const worker :Workerd.Worker = (
  modules = [
    (name = "worker.js", esModule = embed "worker.js"),
    (name = "kekkai_runtime.js", esModule = embed "kekkai_runtime.js"),
    (name = "kekkai_meta.js", esModule = embed "kekkai_meta.js"),
    (name = "module.wasm", wasm = embed "module.wasm"),
  ],
  compatibilityDate = "2026-09-01",
  bindings = [
    (name = "KEKKAI_OUTBOX", text = "${OUTBOX:-log}"),
    (name = "KEKKAI_DO_SHARD", text = "${SHARD:-global}"),
    (name = "KEKKAI_DO", durableObjectNamespace = "KekkaiObject"),
  ],
  durableObjectNamespaces = [(className = "KekkaiObject", uniqueKey = "kekkai-dev-$name", enableSql = true)],
  durableObjectStorage = (localDisk = "state"),
  globalOutbound = "internet",
);
$router
EOF2
echo "serving $file on http://127.0.0.1:$port (state in $out/.state)"
exec workerd serve "$out/workerd.capnp"
