// Package glue generates the JavaScript side of a compiled Kekkai program:
// the runtime (host operations and transactional store adapters), program
// metadata, and a Cloudflare Workers entry point that maps Worker bindings
// to capabilities.
package glue

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/illumination-k/kekkai/internal/ir"
)

//go:embed runtime.js
var Runtime string

// Meta is the program metadata consumed by the runtime.
type Meta struct {
	Strings       []string          `json:"strings"`
	HandlerParams []ir.HandlerParam `json:"handlerParams"`
}

// MetaJS renders kekkai_meta.js.
func MetaJS(m Meta) string {
	if m.Strings == nil {
		m.Strings = []string{}
	}
	b, _ := json.MarshalIndent(m, "", "  ")
	return "// Generated by kek. Do not edit.\nexport default " + string(b) + ";\n"
}

// WorkerJS renders the Workers entry point. Capabilities are created from
// the environment (this is the only place where the program receives
// authority):
//
//   - a `&Db` parameter named `db` uses the D1 binding `DB` through the
//     optimistic key-value adapter (D1KvStore), or, when the Worker has a
//     Durable Object namespace bound as KEKKAI_DO, the storage of the
//     object the request is routed to (DurableObjectStore);
//   - `&Log` is the console, `&Net` is fetch, `&Clock` / `&Random` are the
//     system clock and crypto.getRandomValues.
//
// The outbox is selected with the KEKKAI_OUTBOX variable ("fetch",
// "log", or "queue" with a Queue producer bound as OUTBOX). See
// docs/runtime.md.
func WorkerJS(params []ir.HandlerParam) string {
	var b strings.Builder
	b.WriteString(workerHead)
	for _, p := range params {
		var expr string
		switch p.Kind {
		case "request":
			continue
		case "Db":
			expr = fmt.Sprintf("dbCap(db(%q), outbox(env))", strings.ToUpper(p.Name))
		case "Log":
			expr = "consoleLog()"
		case "Net":
			expr = "fetchNet()"
		case "Clock":
			expr = "systemClock()"
		case "Random":
			expr = "cryptoRandom()"
		default:
			continue
		}
		fmt.Fprintf(&b, "    %s: %s,\n", jsKey(p.Name), expr)
	}
	b.WriteString(workerTail)
	return b.String()
}

const workerHead = `// Generated by kek. Capabilities are created here from Worker bindings;
// this is the only place where the program receives authority.
//
// Configuration (wrangler.toml):
//   [[d1_databases]] DB            D1 database for a ` + "`db: &Db`" + ` parameter (default backend)
//   [[durable_objects.bindings]] KEKKAI_DO (class KekkaiObject)
//                                  route every request into a Durable Object and
//                                  keep Db data in its transactional storage
//   KEKKAI_DO_SHARD = "global" | "segment:N" | "header:NAME" | "query:NAME"
//                                  which object a request goes to (default "global")
//   KEKKAI_OUTBOX = "fetch" | "log" | "queue"
//                                  how outbox entries are delivered after commit
//                                  (default "fetch"; "queue" needs a producer bound as OUTBOX)
import wasm from "./module.wasm";
import meta from "./kekkai_meta.js";
import {
  createKekkai, dbCap, D1KvStore, DurableObjectStore, consoleLog, fetchNet, systemClock, cryptoRandom,
  fetchOutbox, logOutbox, queueOutbox,
} from "./kekkai_runtime.js";

const app = createKekkai(wasm, meta);

function outbox(env) {
  const mode = env.KEKKAI_OUTBOX || (env.OUTBOX ? "queue" : "fetch");
  switch (mode) {
    case "fetch": return fetchOutbox();
    case "log": return logOutbox();
    case "queue":
      if (!env.OUTBOX) throw new Error("KEKKAI_OUTBOX=queue needs a Queue producer binding named OUTBOX");
      return queueOutbox(env.OUTBOX);
    default: throw new Error("unknown KEKKAI_OUTBOX mode " + mode);
  }
}

// db(binding) returns the store backing the Db capability of that binding.
function capabilities(env, db) {
  return {
`

const workerTail = `  };
}

const d1Stores = new WeakMap();
function d1Store(env, binding) {
  const d1 = env[binding];
  if (!d1) throw new Error("missing D1 binding " + binding + " (or bind a Durable Object namespace as KEKKAI_DO)");
  let s = d1Stores.get(d1);
  if (!s) d1Stores.set(d1, (s = new D1KvStore(d1)));
  return s;
}

// The name of the Durable Object a request is routed to. Transactions are
// atomic within one object, so the shard key must cover every key a
// transaction touches (e.g. a tenant or account id in the path).
function shardName(request, env) {
  const spec = env.KEKKAI_DO_SHARD || "global";
  const url = new URL(request.url);
  const [kind, arg] = spec.split(/:(.*)/s);
  let v = null;
  if (kind === "global") v = "global";
  else if (kind === "segment") v = url.pathname.split("/").filter((s) => s !== "")[Number(arg)] ?? null;
  else if (kind === "header") v = request.headers.get(arg);
  else if (kind === "query") v = url.searchParams.get(arg);
  else throw new Error("unknown KEKKAI_DO_SHARD " + spec);
  return v === null || v === "" ? null : kind + ":" + v;
}

export default {
  async fetch(request, env, ctx) {
    if (env.KEKKAI_DO) {
      const name = shardName(request, env);
      if (name === null) return new Response("missing shard key", { status: 400 });
      return env.KEKKAI_DO.get(env.KEKKAI_DO.idFromName(name)).fetch(request);
    }
    return app.handle(request, capabilities(env, (b) => d1Store(env, b)), ctx);
  },

  // Outbox consumer for KEKKAI_OUTBOX = "queue": at-least-once delivery.
  async queue(batch, env) {
    for (const msg of batch.messages) {
      try {
        const r = await fetch(msg.body.url, { method: "POST", body: msg.body.body });
        if (!r.ok) throw new Error("status " + r.status);
        msg.ack();
      } catch (e) {
        console.error("kekkai: outbox delivery failed, will retry:", e);
        msg.retry();
      }
    }
  },
};

// Durable Object running the program next to its storage. Each Db binding
// gets its own key prefix inside the object.
export class KekkaiObject {
  constructor(state, env) {
    this.state = state;
    this.env = env;
    this.stores = new Map();
  }
  store(binding) {
    let s = this.stores.get(binding);
    if (!s) this.stores.set(binding, (s = new DurableObjectStore(this.state.storage, { prefix: binding + ":" })));
    return s;
  }
  async fetch(request) {
    return app.handle(request, capabilities(this.env, (b) => this.store(b)), {});
  }
}
`

// Target selects the storage backend a generated wrangler.toml binds.
type Target string

const (
	TargetD1 Target = "d1" // D1 database, optimistic KV adapter (default)
	TargetDO Target = "do" // Durable Object with transactional storage
)

// WranglerToml renders a starter wrangler.toml for the D1 target.
func WranglerToml(name string, params []ir.HandlerParam) string {
	s, _ := WranglerTomlFor(name, params, TargetD1)
	return s
}

// WranglerTomlFor renders a starter wrangler.toml for a target.
func WranglerTomlFor(name string, params []ir.HandlerParam, target Target) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "name = %q\nmain = \"worker.js\"\ncompatibility_date = \"2026-09-01\"\n", name)
	b.WriteString("\n[vars]\n# How outbox entries are delivered after commit: \"fetch\" | \"log\" | \"queue\" (see docs/runtime.md)\nKEKKAI_OUTBOX = \"fetch\"\n")
	switch target {
	case TargetD1, "":
		for _, p := range params {
			if p.Kind == "Db" {
				fmt.Fprintf(&b, "\n[[d1_databases]]\nbinding = %q\ndatabase_name = %q\ndatabase_id = \"local\"\n",
					strings.ToUpper(p.Name), name+"-"+p.Name)
			}
		}
	case TargetDO:
		b.WriteString("# Which Durable Object a request is routed to: \"global\" | \"segment:N\" | \"header:NAME\" | \"query:NAME\"\nKEKKAI_DO_SHARD = \"global\"\n")
		b.WriteString("\n[[durable_objects.bindings]]\nname = \"KEKKAI_DO\"\nclass_name = \"KekkaiObject\"\n")
		b.WriteString("\n[[migrations]]\ntag = \"v1\"\nnew_sqlite_classes = [\"KekkaiObject\"]\n")
	default:
		return "", fmt.Errorf("unknown target %q (want d1 or do)", target)
	}
	return b.String(), nil
}

func jsKey(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}
