// Package glue generates the JavaScript side of a compiled Kekkai program:
// the runtime (host operations and transactional store adapters), program
// metadata, and a Cloudflare Workers entry point that maps Worker bindings
// to capabilities.
package glue

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/illumination-k/kekkai/internal/ir"
)

//go:embed runtime.js
var Runtime string

// Meta is the program metadata consumed by the runtime.
type Meta struct {
	Strings       []string          `json:"strings"`
	HandlerParams []ir.HandlerParam `json:"handlerParams"`
}

// MetaJS renders kekkai_meta.js.
func MetaJS(m Meta) string {
	if m.Strings == nil {
		m.Strings = []string{}
	}
	b, _ := json.MarshalIndent(m, "", "  ")
	return "// Generated by kek. Do not edit.\nexport default " + string(b) + ";\n"
}

// WorkerJS renders the Workers entry point. Capabilities are created from
// the environment: a `&Db` parameter named `db` uses the D1 binding `DB`
// through the optimistic key-value adapter (replace the adapter to target
// another transactional backend).
func WorkerJS(params []ir.HandlerParam) string {
	var b strings.Builder
	b.WriteString(`// Generated by kek. Capabilities are created here from Worker bindings;
// this is the only place where the program receives authority.
import wasm from "./module.wasm";
import meta from "./kekkai_meta.js";
import {
  createKekkai, dbCap, D1KvStore, consoleLog, fetchNet, systemClock, cryptoRandom,
} from "./kekkai_runtime.js";

const app = createKekkai(wasm, meta);
const stores = new Map();
function store(binding, env) {
  if (!env[binding]) throw new Error("missing D1 binding " + binding);
  if (!stores.has(binding)) stores.set(binding, new D1KvStore(env[binding]));
  return stores.get(binding);
}

export default {
  async fetch(request, env, ctx) {
    const caps = {
`)
	for _, p := range params {
		var expr string
		switch p.Kind {
		case "request":
			continue
		case "Db":
			expr = fmt.Sprintf("dbCap(store(%q, env))", strings.ToUpper(p.Name))
		case "Log":
			expr = "consoleLog()"
		case "Net":
			expr = "fetchNet()"
		case "Clock":
			expr = "systemClock()"
		case "Random":
			expr = "cryptoRandom()"
		default:
			continue
		}
		fmt.Fprintf(&b, "      %s: %s,\n", jsKey(p.Name), expr)
	}
	b.WriteString(`    };
    return app.handle(request, caps, ctx);
  },
};
`)
	return b.String()
}

// WranglerToml renders a starter wrangler.toml.
func WranglerToml(name string, params []ir.HandlerParam) string {
	var b strings.Builder
	fmt.Fprintf(&b, "name = %q\nmain = \"worker.js\"\ncompatibility_date = \"2026-09-01\"\n", name)
	for _, p := range params {
		if p.Kind == "Db" {
			fmt.Fprintf(&b, "\n[[d1_databases]]\nbinding = %q\ndatabase_name = %q\ndatabase_id = \"local\"\n",
				strings.ToUpper(p.Name), name+"-"+p.Name)
		}
	}
	return b.String()
}

func jsKey(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}
